language: php

sudo: false

php:
  - 7
  - 7.1
  - 7.2
  - nightly

env: TMPDIR=/tmp USE_XDEBUG=false

branches:
  only:
    master

install:
 - phpenv rehash

services:
  - memcached

stages:
  - test
  - test with coverage

before_script:
  - if [[ "$USE_XDEBUG" == false ]]; then phpenv config-rm xdebug.ini || return 0; fi
  - phpenv config-add tests/travis.ini
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres

  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != 7* ]]; then phpenv config-add tests/config.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" == 7* ]]; then phpenv config-add tests/php7_config.ini; fi

  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

script:
  - cd tests/
  - php runalltests.php

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - stage: test with coverage
      php: 7.1
      env: TMPDIR=/tmp USE_XDEBUG=true
      script:
        - cd tests/
        - php runalltests.php --coverage
      after_success:
        - cd ..
        - ./bin/phpcov merge ./build/coverage --clover=./build/coverage/clover.xml
        - bash <(curl -s https://codecov.io/bash) -f ./build/coverage/clover.xml
