language: php

sudo: false

php:
  - 5.6
  - 7
  - 7.1
  - 7.2

env: TMPDIR=/tmp

install:
 - phpenv rehash

services:
  - memcached

before_script:
  - phpenv config-rm xdebug.ini || return 0
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres

  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != 7* ]]; then phpenv config-add tests/config.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" == 7* ]]; then phpenv config-add tests/php7_config.ini; fi

  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

script:
 - cd tests/
 - php runalltests.php

matrix:
  allow_failures:
   - php: 7.2
